import React from "react";
import { Feather } from "@expo/vector-icons";
import { Icon } from "react-native-paper";

type Props = {
  name: string;
  size?: number;
  color?: string;
};

const FEATHER_ICON_MAP: Record<string, React.ComponentProps<typeof Feather>["name"]> = {
  account: "user",
  "account-circle": "user",
  "account-details-outline": "user-check",
  "account-group-outline": "users",
  "account-outline": "user",
  "alert-outline": "alert-triangle",
  "alert-circle-outline": "alert-circle",
  archive: "archive",
  "arrow-left": "arrow-left",
  "arrow-right": "arrow-right",
  "airplane": "navigation",
  "bank-outline": "briefcase",
  "bell-outline": "bell",
  "barcode-scan": "grid",
  "briefcase-outline": "briefcase",
  calendar: "calendar",
  "calendar-outline": "calendar",
  camera: "camera",
  check: "check",
  "check-circle": "check-circle",
  "checkbox-multiple-outline": "check-square",
  "checkbox-outline": "check-square",
  "chevron-down": "chevron-down",
  "chevron-left": "chevron-left",
  "chevron-right": "chevron-right",
  "chevron-up": "chevron-up",
  clipboard: "clipboard",
  "clipboard-outline": "clipboard",
  cloud: "cloud",
  "cloud-outline": "cloud",
  code: "code",
  "code-braces": "code",
  "code-brackets": "code",
  "code-tags": "code",
  "content-copy": "copy",
  "content-save": "save",
  copy: "copy",
  "cog-outline": "settings",
  "card-account-details-outline": "user-check",
  "card-text-outline": "type",
  "credit-card-chip-outline": "credit-card",
  "credit-card-multiple-outline": "credit-card",
  "credit-card-outline": "credit-card",
  database: "database",
  "database-outline": "database",
  "delete-sweep-outline": "trash-2",
  dialpad: "hash",
  "dots-horizontal": "more-horizontal",
  drag: "move",
  download: "download",
  edit: "edit-2",
  "email-outline": "mail",
  "file-import-outline": "download",
  "file-document-outline": "file-text",
  filter: "filter",
  "filter-variant-plus": "filter",
  folder: "folder",
  "folder-outline": "folder",
  "form-textbox-password": "lock",
  "format-title": "type",
  "gamepad-variant-outline": "play",
  "gift-outline": "gift",
  globe: "globe",
  "google-chrome": "chrome",
  help: "help-circle",
  "help-circle-outline": "help-circle",
  home: "home",
  "home-outline": "home",
  "heart-pulse": "heart",
  import: "download",
  information: "info",
  "information-outline": "info",
  "keyboard-outline": "command",
  key: "key",
  "key-outline": "key",
  "key-variant": "key",
  "list-status": "list",
  history: "clock",
  lock: "lock",
  "lock-outline": "lock",
  "lock-check-outline": "lock",
  "log-out": "log-out",
  magnify: "search",
  menu: "menu",
  minus: "minus",
  monitor: "monitor",
  "monitor-screenshot": "monitor",
  moon: "moon",
  "map-marker-outline": "map-pin",
  "music-note-outline": "music",
  "note-outline": "file-text",
  "office-building-outline": "briefcase",
  "open-in-new": "external-link",
  palette: "sliders",
  paperclip: "paperclip",
  "pencil-outline": "edit-2",
  "phone-outline": "phone",
  "pin-off-outline": "x",
  "pin-outline": "map-pin",
  "playlist-remove": "list",
  plus: "plus",
  "puzzle-outline": "package",
  qrcode: "grid",
  "qrcode-scan": "grid",
  refresh: "refresh-cw",
  save: "save",
  search: "search",
  "school-outline": "book-open",
  "server-network-outline": "server",
  settings: "settings",
  "shopping-outline": "shopping-cart",
  "shield-outline": "shield",
  "shield-check-outline": "shield",
  smartphone: "smartphone",
  cellphone: "smartphone",
  "sort-variant": "sliders",
  "sort-descending": "bar-chart-2",
  "star": "star",
  "star-off-outline": "star",
  "star-outline": "star",
  sun: "sun",
  sync: "refresh-cw",
  "theme-light-dark": "sun",
  "tooltip-account": "mouse-pointer",
  trash: "trash-2",
  "trash-can-outline": "trash-2",
  "two-factor-authentication": "shield",
  "tag": "tag",
  "tag-outline": "tag",
  "undo-variant": "rotate-ccw",
  update: "refresh-cw",
  upload: "upload",
  "redo-variant": "rotate-cw",
  user: "user",
  users: "users",
  wallet: "credit-card",
  "wallet-outline": "credit-card",
  web: "globe",
  "web-remove": "globe",
  wifi: "wifi",
};

function AppIcon({ name, size = 20, color }: Props) {
  const featherName = FEATHER_ICON_MAP[name];

  if (featherName) {
    return <Feather name={featherName} size={size} color={color} />;
  }

  return <Icon source={name} size={size} color={color} />;
}

export default AppIcon;
