name: Deploy Homepage to gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repository (master branch)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # wichtig für andere Branches wie gh-pages

      - name: Clone gh-pages branch
        run: |
          git clone --depth=1 --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages

      - name: Copy homepage files into gh-pages
        run: |
          cp -r homepage/* gh-pages/

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update homepage content" || echo "No changes to commit"
          git push origin gh-pages