name: Deploy Homepage and Keep updater.json on gh-pages

on:
  push:
    branches:
      - master  # Oder der Branch, den du verwendest (z.B. master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Git
        run: sudo apt-get install git

      - name: Clone gh-pages branch
        run: |
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          cd gh-pages
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
      - name: Copy homepage files and updater.json to gh-pages
        run: |
          # We copy the content from the 'homepage' folder to 'gh-pages'
          cp -r ../homepage/* ./  # Kopiere alle Dateien aus dem 'homepage' Ordner in den gh-pages Branch
          # Sicherstellen, dass die updater.json im gh-pages Branch bleibt
          cp ../updater.json ./  # Kopiere die updater.json nicht zu überschreiben

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Deploy new homepage content and update updater.json" || echo "No changes to commit"
          git push origin gh-pages