name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-tauri:
    runs-on: ubuntu-22.04
    env:
      TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Setup Rust & Tauri
        uses: tauri-apps/tauri-action@v0.4

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/rpm/*.rpm
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/appimage/*.tar.gz
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/macos/*.zip
          body: "Fixes and improvements in this release."

  update-expo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install eas-cli
        run: npm install --global eas-cli

      - name: Publish Expo Update
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx eas update --branch production --message "Release for ${{ github.ref_name }}"

  update-json:
    needs: [build-tauri]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update updater.json
        run: |
          echo '{
            "version": "${{ github.ref_name }}",
            "notes": "Neue Version mit Bugfixes",
            "pub_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "platforms": {
              "windows-x86_64": {
                "url": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/app-windows.exe"
              },
              "linux-x86_64": {
                "url": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/app-linux.AppImage"
              },
              "darwin-x86_64": {
                "url": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/app-macos.dmg"
              }
            }
          }' > updater.json

      - name: Commit and push updater.json
        run: |
          git add updater.json
          git commit -m "Update updater.json for version ${{ github.ref_name }}"
          git push origin master